### ISSUE TITLE
cUtil().unescape

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#137]
Une erreur avec film_illimit

`10:00:25 T:6608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 169, in <module>
                                                main()
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 81, in parseUrl
                                                exec "plugin."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\film_illimit_fr.py", line 160, in showMovies
                                                sName = cUtil().unescape(sName)
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\util.py", line 109, in unescape
                                                return re.sub("&#?\w+;", fixup, text)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\re.py", line 151, in sub
                                                return _compile(pattern, flags).sub(repl, string, count)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--`

J'en ai conclue que cUtil().unescape ne supporter pas le tag `&#8217;` mais je sais pas pourquoi.

**Comment by TmpName** [comment]
Encore une salete de convertion unicode, j en fais des cauchemars la nuit.
La fonction unescape ne fonctionne pas en unicode.
J'ai modifier la source pour que cella fonctionne.

**Comment by LordVenom** [comment]
Ok ça fonctionne merci perso j'ai corriger la recherche de megastream,
