### ISSUE TITLE
Recherche visuelle : Désactiver le menu contextuel Alluc

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#138]
Bonjour,
Je viens de découvrir la recherche manuelle que je n'avais pas encore utilisé : 
C'est très class !

Par contre quand on sélectionne un film ca ouvre un menu contextuel pour choisir entre vstream et alluc.

Perso ca marche à tout les coups avec vstream alors je me demandais comment désactiver ce menu contextuel et directement lancer la recherche avec vStream ?

Merci d'avance pour votre aide

**Comment by TmpName** [comment]
Dans themoviesdb_org.py
Remplace
>>    dialog3 = xbmcgui.Dialog()
    ret = dialog3.select('Selectionner un Moteur de Recherche',['Vstream (Fiable mais plus complexe)','Alluc (Simple mais resultats non garantis)'])

    if ret == 0:
        VstreamSearch(sMovieTitle)
    elif ret == 1:
        AllucSearch(sMovieTitle + sExtraTitle)

par 
>>VstreamSearch(sMovieTitle)

**Comment by canopre** [comment]
Top : Merci

**Comment by canopre** [comment]
Je viens de faire un essai : je crois avoir bien suivi tes instructions mais j'ai une erreur vstream quand je clique sur un film.

Je joins mes logs : http://pastebin.com/q59YW6eC

Merci d'avance pour ton aide.

**Comment by canopre** [comment]
C nickel : merci !

**Comment by canopre** [comment]
Pour reparler de la recherche visuelle : 
Je trouve la fonction super pratique mais j'ai un petit problème avec la recherche par acteur populaire :

Il n'y a "que" 3 films par acteurs qui s'affichent et si je clique sur le nom d'un acteur pour en voir + :

Je reviens à la liste des acteurs sans pouvoir accéder à plus de films du même acteur.

C'est peut-être normal ?

**Comment by TmpName** [comment]
Pour le nbre de resultat c'est l'API qui veut ca, en fait c'est une recherche, et ils estiment que si en 20 resulats tu n'as pas trouve ce que tu cherches c'est que tu as mal formule ta demande ^^.

Je t'ai mis une correction pour les acteurs, now tu as une liste de film qui va apparaitre, mais c'est TOUT les films meme si l'acteur a juste donne sa voix pour un film d'animation pr exmple.

**Comment by canopre** [comment]
Je vais regarder la nouvelle fonctions "Acteurs" : Merci.

Par contre pour la recherche visuelle de films : Le résultat affiche 21 films par page : Est-ce possible d'augmenter ou de diminuer cette valeur ?

Je pensais au nombre de films qui s'affichent quand on utilise la fonction recherche visuelle + Par exemple : Films par genre : Il y a 20 films + le bouton next par page : Peux t'on modifier cette valeur ?

**Comment by TmpName** [comment]
Non, c'est L'api qui est regle comme ca, y en a qui leurs ont fait la demande, c'est rejette, en fait c'est une recherche sur les nouveaute et toute leur recherche sont bloque a 20 resultats max par page.

**Comment by canopre** [comment]
ok Alors :)

**Comment by canopre** [comment]
En appliquant ta modif et depuis la dernière mise à jour je ne peux plus utiliser la recherche avec cette vilaine erreur en logs :-( Une idée ?

07:06:31 8501.176758 T:1568404464  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
07:06:32 8501.598633 T:1568404464  NOTICE: 	[PLUGIN] Vstream: load site themoviedb_org and call function load
07:06:32 8502.170898 T:1568404464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('unindent does not match any outer indentation level', ('/home/osmc/.kodi/addons/plugin.video.vstream/resources/sites/themoviedb_org.py', 580, 30, '   VstreamSearch(sMovieTitle)\n'))
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vstream/default.py", line 169, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.vstream/default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "/home/osmc/.kodi/addons/plugin.video.vstream/default.py", line 80, in parseUrl
                                                exec "from resources.sites import " + sSiteName + " as plugin"
                                              File "<string>", line 1, in <module>
                                            IndentationError: ('unindent does not match any outer indentation level', ('/home/osmc/.kodi/addons/plugin.video.vstream/resources/sites/themoviedb_org.py', 580, 30, '   VstreamSearch(sMovieTitle)\n'))
                                            -->End of Python script error report<--
07:06:32 8502.204102 T:1956959152   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=%5bCOLOR%20gray%5dRecherche%20visuelle%5b%2fCOLOR%5d
07:06:32 8502.206055 T:1956959152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=%5bCOLOR%20gray%5dRecherche%20visuelle%5b%2fCOLOR%5d) failed
07:06:33 8503.437500 T:1699132400  NOTICE: Hole Umgebung

**Comment by TmpName** [comment]
Probleme d'indent, c'est le nbre d'espaces (et surtout pas tabulations) qui n'est pas conforme.

**Comment by canopre** [comment]
ah ok.... je savais même pas qu'il fallait faire attention à ca !  Merci !!!

**Comment by TmpName** [comment]
Ouais je t'avous, moi aussi j'etais sur le cul quand j'ai appris ca, suis vraiment pas fan du python comme language.

**Comment by canopre** [comment]
C'était bien ça : 1000 mercis !
